apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${REPO}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${REPO}
  template:
    metadata:
      labels:
        app: ${REPO}
    spec:
      restartPolicy: Always
      containers:
      - name: ${REPO}
        image: ${ORIGIN_REPO}/${REPO}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ${REPO}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: ${REPO}
  selector:
    app: ${REPO}
